name: CI

on:
  push:
    branches: [main]
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: [stable, unstable, development-target]
    container:
      image: ghcr.io/elementary/docker:${{ matrix.version }}

    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: |
        apt update
        apt install -y meson libedataserver1.2-dev libglib2.0-dev libgranite-7-dev libgtk-4-dev libadwaita-1-dev libswitchboard-3-dev valac
    - name: Build
      env:
        DESTDIR: out
      run: |
        meson build
        ninja -C build
        ninja -C build install

  fedora:
    runs-on: ubuntu-latest

    container:
      image: fedora:latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          dnf install -y git meson ninja-build vala evolution-data-server-devel glib2-devel granite-devel gtk3-devel libhandy-devel
          git clone --depth 1 --branch 6.0.2 https://github.com/elementary/switchboard
          dnf install -y libgee-devel
          cd switchboard
          meson build --prefix=/usr
          ninja -C build
          ninja -C build install
          cd ..
          rm -rf switchboard
      - name: Build
        env:
          DESTDIR: out
        run: |
          meson build
          ninja -C build
          ninja -C build install

  lint:

    runs-on: ubuntu-latest

    container:
      image: valalang/lint

    steps:
    - uses: actions/checkout@v3
    - name: Lint
      run: io.elementary.vala-lint -d .
